import { useEffect, useState } from 'react';
import AdminLayout from '../../components/AdminLayout';
import axiosClient from '../../api/axiosClient';

export default function AdminReports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  async function loadReports() {
    setLoading(true);
    try {
      const { data } = await axiosClient.get('/admin/reports');
      setReports(data.reports);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { loadReports(); }, []);

  return (
    <AdminLayout>
      <div className="max-w-7xl mx-auto">
        <h1 className="text-3xl font-bold text-slate-800 mb-2">📋 Reports</h1>
        <p className="text-slate-500 mb-8">View system-generated reports and analytics data.</p>

        {loading ? (
          <p className="text-slate-500 text-center py-10">Loading reports…</p>
        ) : (
          <div className="rounded-2xl bg-white shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead className="bg-violet-50">
                  <tr>
                    <th className="px-6 py-4 text-sm font-semibold text-violet-700">Type</th>
                    <th className="px-6 py-4 text-sm font-semibold text-violet-700">Generated By</th>
                    <th className="px-6 py-4 text-sm font-semibold text-violet-700">Student</th>
                    <th className="px-6 py-4 text-sm font-semibold text-violet-700">Date</th>
                    <th className="px-6 py-4 text-sm font-semibold text-violet-700">Data</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {reports.map((report) => (
                    <tr key={report.id} className="hover:bg-violet-50/50 transition">
                      <td className="px-6 py-4 font-medium text-slate-800">{report.report_type}</td>
                      <td className="px-6 py-4 text-sm text-slate-600">{report.generated_by_name}</td>
                      <td className="px-6 py-4 text-sm text-slate-600">{report.student_name || '—'}</td>
                      <td className="px-6 py-4 text-sm text-slate-500">
                        {new Date(report.created_at).toLocaleString()}
                      </td>
                      <td className="px-6 py-4">
                        <pre className="text-xs text-slate-500 max-w-xs overflow-hidden truncate">
                          {JSON.stringify(report.data)}
                        </pre>
                      </td>
                    </tr>
                  ))}
                  {reports.length === 0 && (
                    <tr>
                      <td colSpan={5} className="px-6 py-10 text-center text-slate-500">No reports found.</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </AdminLayout>
  );
}